# em 0  # *Joy and Sad
# em 1  # *Trust and Disgust
# em 2  # *Fear and Anger
# em 3  # *Surprise and Anticipation

emotionsDict = {
    # em 0 serenity 1
    'calm': [0, 1],
    'calming': [0, 1],
    'calmed': [0, 1],
    'peaceful': [0, 1],
    'relax': [0, 1],
    'relaxing': [0, 1],
    'relaxed': [0, 1],
    'pleasing': [0, 1],
    'good': [0, 1],
    # em 0 joy 2
    'happy': [0, 2],
    'excited': [0, 2],
    'exciting': [0, 2],
    'pleased': [0, 2],
    'pleasing': [0, 2],
    'better': [0, 2],
    # em 0 ecstasy 3
    'delighted': [0, 3],
    'giddy': [0, 3],
    'best': [0, 3],
    # em 0 Pensiveness -1
    'sorrow': [0, -1],
    'sorrows': [0, -1],
    'sorrowing': [0, -1],
    'sorrowed': [0, -1],
    'miserable': [0, -1],
    'bad': [0, -1],
    # em 0 sadness -2
    'sad': [0, -2],
    'sadden': [0, -2],
    'unhappy': [0, -2],
    'regret': [0, -2],
    'regreting': [0, -2],
    'disappointed': [0, -2],
    'disappointing': [0, -2],
    'worse': [0, -2],
    # em 0 grief -3
    'heartbroken': [0, -3],
    'heartbreaking': [0, -3],
    'distraught': [0, -3],
    'distraughted': [0, -3],
    'worst': [0, -3],
    # em 1 acceptance 1
    'open': [1, 1],
    'welcoming': [1, 1],
    'receiving': [1, 1],
    # em 1 trust 2
    'accept': [1, 2],
    'accepting': [1, 2],
    'safe': [1, 2],
    'trust': [1, 2],
    'belive': [1, 2],
    'belives': [1, 2],
    'faith': [1, 2],
    'want': [1, 2],
    # em 1 admiration 3
    'appreciate': [1, 3],
    'appreciating': [1, 3],
    'respect': [1, 3],
    'respectful': [1, 3],
    'admire': [1, 3],
    'admiring': [1, 3],
    'admirable': [1, 3],
    'love': [1, 3],
    'loved': [1, 3],
    'loving': [1, 3],
    'lovely': [1, 3],
    # em 1 boredom -1
    'tired': [1, -1],
    'uninterested': [1, -1],
    'uninteresting': [1, -1],
    'flat': [1, -1],
    # em 1 disgust -2
    'distrust': [1, -2],
    'distrusting': [1, -2],
    'doubt': [1, -2],
    'reject': [1, -2],
    'bitter': [1, -2],
    # em 1 loathing -3
    'disturb': [1. -3],
    'disturbing': [1. -3],
    'dislike': [1, -3],
    'hate': [1, -3],
    'hated': [1, -3],
    'hates': [1, -3],
    'disgust': [1, -3],
    'disgustful': [1, -3],
    'disgusted': [1, -3],
    'disgusting': [1, -3],
    # em 2 apprehention 1
    'worried': [2, 1],
    'worry': [2, 1],
    'worrying': [2, 1],
    'anxious': [2, 1],
    'anxiety': [2, 1],
    'concern': [2, 1],
    'concerned': [2, 1],
    'concerning': [2, 1],
    'messy': [2, 1],
    # em 2 fear 2
    'scare': [2, 2],
    'scary': [2, 2],
    'scared': [2, 2],
    'uneasy': [2, 2],
    'distress': [2, 2],
    'distressed': [2, 2],
    # em 2 terror 3
    'alarmed': [2, 3],
    'petrified': [2, 3],
    'terrified': [2, 3],
    'terrifying': [2, 3],
    # em 2 Annoyance -1
    'frustrated': [2, -1],
    'frustrate': [2, -1],
    'frustrating': [2, -1],
    'prickly': [2, -1],
    'agitated': [2, -1],
    # em 2 Anger -2
    'annoyance': [2, -2],
    'irritation': [2, -2],
    'outrage': [2, -2],
    'irritability': [2, -2],
    'displeasure': [2, -2],
    'fury': [2, -2],
    # em 2 rage -3
    'outburst': [2, -3],
    'resentment': [2, -3],
    'bitterness': [2, -3],
    'temper': [2, -3],
    'tantrum': [2, -3],
    # em 3 distraction 1
    'interruption': [3, 1],
    'complication': [3, 1],
    'disturbance': [3, 1],
    'interrupted': [3, 1],
    'hindrance': [3, 1],
    'interference': [3, 1],
    # em 3 surprise 2
    'amazement': [3, 2],
    'flabbergast': [3, 2],
    'startle': [3, 2],
    'astonish': [3, 2],
    'astonised': [3, 2],
    'astonishing': [3, 2],
    # em 3 amazement 3 
    'perplexity': [3, 1],
    'surprise': [3, 1],
    'surprsed': [3, 1],
    'bewilderment': [3, 1],
    'shock': [3, 1],
    # em 3 interest -1
    'enthusiasm': [3, -1],
    'intrigue': [3, -1],
    'fascinate': [3, -1],
    'fascinated': [3, -1],
    'attentiveness': [3, -1],
    'curiosity': [3, -1],
    # em 3 Anticipation -2
    'expectation': [3, -2],
    'prospect': [3, -2],
    'excitement': [3, -2],
    'excited': [3, -2],
    'hope': [3, -2],
    'prediction': [3, -2],
    # em 3 vigilance -3
    'alertness': [3, -3],
    'surveillance': [3, -3],
    'caution': [3, -3],
    'diligence': [3, -3],
    'concern': [3, -3],
    'concerning': [3, -3],
    'concerned': [3, -3],
    # modifier
    'too': [4, 2],
    'so': [4, 2],
    'very': [4, 2],
    'lot': [4, 3],
    'really': [4, 3],
    'no': [4, -2],
    'zero': [4, -2],
    
}
